{
 "title": "Homework_10_3",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Panel CPU Idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[10s])) * 100",
     "legendFormat": "{{hostmane}}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "LA1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"} ",
     "legendFormat": "LA5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "LA15"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"nodeexporter\"}",
     "legendFormat": "Memory Available"
    }
   ]
  },
  {
   "title": "Avail space on FS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"nodeexporter\",fstype!~\"tmpfs|fuse.lxcfs|fuse.xrdp-chansrv\"}",
     "legendFormat": "{{mountpoint}} on {{device}}"
    }
   ]
  }
 ]
}