---
  - name: Ensure files dir exists
    file:
      state: "directory"
      path: "files"
      mode: '0755'
    delegate_to: 127.0.0.1
  - name: Check state of Logstash archive
    stat:
      path: "files/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
    register: logstash_archive_state
    delegate_to: 127.0.0.1  
  - name: Upload tar.gz Logstash from remote URL
    get_url:
      url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
      dest: "files/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
      mode: '0644'
      timeout: 60
      force: true
    register: get_logstash
    until: get_logstash is succeeded
    when: not logstash_archive_state.stat.exists
    delegate_to: 127.0.0.1
  - name: Create directrory for Logstash
    become: true
    file:
      state: directory
      path: "{{ logstash_home }}"
      mode: '0755'
      owner: "{{ ansible_user | default(omit) }}"
  - name: Copy Logstash archive to test stands
    copy:
      src: "logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
      dest: "{{ logstash_archive_path }}"
      mode: '0644'
  - name: Extract Logstash in the installation directory
    become: true
    unarchive:
      copy: false
      src: "{{ logstash_archive_path }}"
      dest: "{{ logstash_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ logstash_home }}/bin/logstash"
      owner: "{{ ansible_user | default(omit) }}"
    tags: skip_ansible_lint
  - name: Set environment Logstash
    become: yes
    template:
      src: templates/logstash.sh.j2
      dest: /etc/profile.d/logstash.sh
      mode: '0755'
  - name: Generate config for Logstash
    become: yes
    template:
      src: logstash.conf.j2
      dest: "{{ logstash_home }}/config/logstash.conf"
      mode: '0644'
      owner: "{{ ansible_user | default(omit) }}"