# Warning: This file is Ansible Managed, manual changes may be overwritten on playbook run.
---
  elasticsearch:
    hosts:
      node01_172.30.155.61:
        ansible_host: 172.30.155.61
        ansible_ssh_private_key_file: private_keys/node01_172.30.155.61
        ansible_user: vagrant
  kibana:
    hosts:
      node01_172.30.155.61:
        ansible_host: 172.30.155.61
        ansible_ssh_private_key_file: private_keys/node01_172.30.155.61
        ansible_user: vagrant
  logstash:
    hosts:
      node02_172.30.151.186:
        ansible_host: 172.30.151.186
        ansible_ssh_private_key_file: private_keys/node02_172.30.151.186
        ansible_user: vagrant
